<a href="https://colab.research.google.com/github/diperezp/Analisis_Se-al_2025_1/blob/main/Optica/OpticaGeometricaMatricial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# $Optica\ Geometrica\ Matricial$

## $Librerias\ a\ utilizar$

In [140]:
#pip install numpy matplotlib

In [141]:
import numpy as np                  #manejo de matrices
import math                         #libreria de matematicas
import matplotlib.pyplot as plt     #libreria para graficar

## $Matrices\ de\ Transformacion$

### $Matriz\ de\ refracción$
$$\begin{pmatrix} 1& -\textit{P} \\ 0 & 1\end{pmatrix}$$

$\textit{P}\rightarrow poder\ de\ la\ interfase$

$$P = \frac{n_t-n_i}{R}$$


*   $n_i \rightarrow indice\ de\  incidencia$
*   $n_t \rightarrow indice\ de\ refraccion$
*   $R  \rightarrow radio\ de\ la\ interfase$

In [142]:
"""Esta funcion devuelve la matriz de de refraccion
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   nt=float()--->indice de refraccion del medio transmitido
   R=float()--->radio
   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de refraccion
   """
def Ra(n_i,n_t,R):
    P=(n_t-n_i)/R #poder del sistema
    return np.array([[1,-P],[0,1]])

print(Ra(1,1.5,10))

[[ 1.   -0.05]
 [ 0.    1.  ]]


### $Matriz\ de\ reflexión$

$$\begin{pmatrix} 1& \frac{2n_i}{R} \\ 0 & 1\end{pmatrix}$$


*   $n_i \rightarrow indice\ de\  incidencia$
*   $R  \rightarrow radio\ de\ la\ interfase$






In [143]:
"""Esta funcion devuelve la matriz de reflexion de
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   R=float()--->radio de la interfase
   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de reflexion
   """
def Re(n_i,R):

    return np.array([[1,2*n_i/R],[0,1]])

print(Re(1,10))

[[1.  0.2]
 [0.  1. ]]


### $Matriz\ de\ translacion$

$$\begin{pmatrix} 1& 0 \\ \frac{D_{12}}{n_{12}} & 1\end{pmatrix}$$


* $D_{12} \rightarrow distancias\ entre\ los\ dos\ vertices\ de\ la\ lente$
* $n_{12}  \rightarrow indice\ de\ refraccion\ de\ la\ lente$

In [144]:
"""Esta funcion devuelve la matriz de reflexion de
   una interfase
   Paramaters:
   ----------------------
   D=float()--->distancia entre los dos vertices de la lente
   n=float()--->indice de refraccion de la lente
   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de traslación
   """
def T(D,n):
    return np.array([[1,0],[D/n,1]])
print(T(1,1.5))

[[1.         0.        ]
 [0.66666667 1.        ]]


### $Matriz\ de\ lente\ gruesa$

---
$M_{L_{gruesa}}=R_{aV'}T_{VV'}R_{aV}$

*   $R_{aV} → Matriz\ del\ primer\ vertice\ V$
*   $T_{VV'} → Matriz\ de\ traslacion\ entre\ vertices\  V→V'$
*   $R_{aV'} → Matriz\ del\ segundo\ vertice\ V'$

$$\begin{pmatrix} 1 - (\frac{P_{V'}D_l}{n_l})& -P_{V}-P_{V'}+(\frac{P_{V}P_{V'}D_l}{n_l}) \\ \frac{D_l}{n_l} &1 - (\frac{P_{V}D_l}{n_l})\end{pmatrix}$$


*   $n_l → indice\ de\ refraccion\ de\ la\ lente$
*   $D_l → grosor\ de\ la\ lente$
*   $P_{V}=\frac{n_l-n}{R} → poder\ del\ vertice\ V $
*   $P_{V'}=\frac{n'-n_l}{R'} → poder\ del\ vertice\ V' $
*   $n → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V$
*   $n' → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V'$





In [145]:
"""Esta funcion devuelve la matriz de de refraccion
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   R_1=float()--->radio del primer vertice
   n_l=float()--->indice de refraccion de la lente
   D=float()--->grosor de la lente
   R_2=float()--->radio del segundo vertice
   nt=float()--->indice de refraccion del medio transmitido

   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de refraccion
   """
def Lg(n,R_1,n_l,D,R_2,nt):
    P_1=(n_l-n)/R_1
    P_2=(nt-n_l)/R_2
    return np.array([[1-(P_1*D/n_l),-P_2-P_1+(P_1*P_2*D/n_l)],[D/n_l,1-(P_2*D/n_l)]])

def LgM(n,R_1,n_l,D,R_2,nt):
    Ra1=Ra(n,n_l,R_1)
    T1=T(D,n_l)
    Ra2=Ra(n_l,nt,R_2)
    return np.dot(np.dot(Ra1,T1),Ra2)

print(Lg(1,np.inf,1.5,0.15,-0.5,1))
print(LgM(1,np.inf,1.5,0.15,-0.5,1))

[[ 1.  -1. ]
 [ 0.1  0.9]]
[[ 1.  -1. ]
 [ 0.1  0.9]]


### $Matriz\ de\ lente\ delgada$

---
$M_{L_{gruesa}}=R_{aV'}T_{VV'}R_{aV}$

*   $R_{aV} → Matriz\ del\ primer\ vertice\ V$
*   $T_{VV'} → Matriz\ de\ traslacion\ entre\ vertices\  V→V'$
*   $R_{aV'} → Matriz\ del\ segundo\ vertice\ V'$

$$M_{L_{gruesa}} = \begin{pmatrix} 1 - (\frac{P_{V'}D_l}{n_l})& -P_{V}-P_{V'}+(\frac{P_{V}P_{V'}D_l}{n_l}) \\ \frac{D_l}{n_l} &1 - (\frac{P_{V}D_l}{n_l})\end{pmatrix}$$


*   $n_l → indice\ de\ refraccion\ de\ la\ lente$
*   $D_l ≈ 0 → lente\ delgada$
*   $P_{V}=\frac{n_l-n}{R} → poder\ del\ vertice\ V $
*   $P_{V'}=\frac{n'-n_l}{R'} → poder\ del\ vertice\ V' $
*   $n → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V$
*   $n' → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V'$

$$ M_{L_{delgada}} = \begin{pmatrix} 1 & -P_{L_{delgada}}\\ 0 &1\end{pmatrix}$$

*   $P_{L_{delgada}}= P_{V}+P_{V'}$


* $P_{L_{delgada}}= \frac{n_l-n}{R} + \frac{n'-n_l}{R'}$

* $ para\ n=n'=1\ se\ tiene\ que:$

* $P_{L_{delgada}}= (n_l-1)\frac{1}{R} - \frac{1}{R'} → Ecuacion\ del\ fabricante\ $

In [146]:
"""Esta funcion devuelve la matriz de de refraccion
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   R_1=float()--->radio del primer vertice
   n_l=float()--->indice de refraccion de la lente
   R_2=float()--->radio del segundo vertice
   nt=float()--->indice de refraccion del medio transmitido

   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de refraccion
   """

def Ld(n,R_1,n_l,R_2,nt):
    P_1=(n_l-n)/R_1
    P_2=(nt-n_l)/R_2
    return np.array([[1,-P_1-P_2],
                     [0,1]])

def LdM(n,R_1,n_l,R_2,nt):
    Ra1=Ra(n,n_l,R_1)
    T1=T(0,n_l)
    Ra2=Ra(n_l,nt,R_2)
    return np.dot(np.dot(Ra1,T1),Ra2)

print(Ld(1,10,1.5,np.inf,1))
print(LdM(1,10,1.5,np.inf,1))

[[ 1.   -0.05]
 [ 0.    1.  ]]
[[ 1.   -0.05]
 [ 0.    1.  ]]


### $$Planos\ principales$$


$M_{HH'}= T_{V'H'}M_{HH'}T_{VH}$

$T_{HV}=\begin{pmatrix} 1& 0 \\ \frac{D}{n} & 1\end{pmatrix}\\
M_{VV'}= \begin{pmatrix} M_{11} & M_{12} \\ M_{21} & M_{22}\end{pmatrix}\\
T_{H'V'}=\begin{pmatrix} 1& 0 \\ \frac{D'}{n'} & 1\end{pmatrix}$

$$M_{HH'}= \begin{pmatrix} M_{11}+\frac{M_{12}D}{n} & M_{12}\\ \frac{M_{11}D'}{n'}+\frac{M_{12}DD'}{nn'}+M_{21}+\frac{M_{22}D}{n}&M_{22}+\frac{M_{12}D'}{n'} \end{pmatrix}$$

$$T_{H'V'}=\begin{pmatrix} 1& -P_{sistema} \\ 0 & 1\end{pmatrix}$$

$\therefore$

$M_{11}+\frac{M_{12}D}{n}=1 ⇒ \overline{HV}=D=(\frac{n}{M_{12}})(1-M_{11})$

$M_{22}+\frac{M_{12}D'}{n'}=1 ⇒ \overline{V'H'}=D'=(\frac{n'}{M_{12}})(1-M_{22})$

$M_{12}=-P_{sistema}$

$P_{sistema}=\frac{nM_{11}}{D} + \frac{n'M_{22}}{D'}+\frac{nn'M_{21}}{DD'}$




In [147]:
"""
Funcion devulve los parametros de los planos principales
relacionados a una matriz de un sistema optico
"""

class PlanosPrincipales():
    def __init__(self,matriz,n=1,np=1):
        self.matriz=matriz
        self.n=n
        self.np=np

    def D(self,n=1 # indice a la izquierda del sistema optico
          ):
        return (n/self.matriz[0,1])*(1-self.matriz[0,0])
    def Dp(self,n=1 #indice a la derecha del sistema optico
           ):
        return (n/self.matriz[0,1])*(1-self.matriz[1,1])
    def poder_sistema(self):
        return -self.matriz[0,1]
    def matriz_plano_principal(self):
        return np.array([[1,-self.poder_sistema()],[0,1]])

    def foco_principal_objeto(self,n=1 #indice a la izquierda del sistema optico
                              ):
        return n/self.poder_sistema()
    def foco_principal_imagen(self,n=1 #indice a la derecha del sistema optico
                              ):
        return n/self.poder_sistema()

## $ Formacion\ de\ Imagenes$


$M_{OI}=T_{H'I}M_{HH'}T_{OH}$
$=\begin{pmatrix} 1&0\\ \frac{s'}{n'}&1 \end{pmatrix} \begin{pmatrix} 1&-P_{sistema}\\ 0&1\end{pmatrix} \begin{pmatrix} 1&0\\ \frac{s}{n}&1\end{pmatrix}$


$$M_{OI}=\begin{pmatrix} 1-\frac{s}{n}P_{sistema}& P_{sistema}\\\frac{s'}{n'}+\frac{s}{n}-\frac{ss'}{nn'}P_{sistema}&1-\frac{s'}{n'}P_{sistema} \end{pmatrix}$$


$\text{Como se trata de una transformacion entre planos conjugados, entonces la matriz debe de tener la forma de:}$

$M_{OI}=\begin{pmatrix} \frac{n'}{n}m_{α}&M_{12}\\0&m_{x} \end{pmatrix} \therefore$

$\frac{n'}{s'}+\frac{n}{s}=P_{sistema}$

$m_{x}=1-\frac{s'}{n'}P_{sistema}$

$m_{α}=\frac{n}{n'}(1-\frac{s}{n}P_{sistema})$



In [148]:
#clase de formacion de imagen
"""Falta corregir el codigo este codigo no sirve y no esta probado"""
class FormacionImagen(PlanosPrincipales):
    def __init__(self,matriz,n=1,np=1,d=0):
        super().__init__(matriz,n,np)
        self.d=d #distancia entre el objeto y el vertice V

    def distanciaOH(self):

      #calculamos la distancia entre el objeto y el plano H
      s= -self.D()+self.d
      return s
    def distanciaHpI(self):
      sp= self.np/(self.poder_sistema()-(self.n/self.distanciaOH()))
      return sp

    def distanciaVpI(self):
      return self.distanciaHpI()+self.Dp()

    def mx(self):
      mx=1-(self.distanciaHpI()/self.np)*self.poder_sistema()
      return mx

    def ma(self):
      return (self.n/self.np)*(1-(self.distanciaOH()/self.n)*self.poder_sistema())


##$Ejercicio\ del\ taller$

In [149]:
#matriz de refraccion 1
n_e=1
n_l1=1.6186
R1=48.88
Ra_1=Ra(n_e,n_l1,R1)
print(Ra_1)
#matriz de traslacion 1
D1=8.89
T1=T(D1,n_l1)
print(T1)
#matriz de refraccion 2
R2=182.96
Ra_2=Ra(n_l1,n_e,R2)
print(Ra_2)
#matriz de traslacion 2
D2=0.38
T2=T(D2,n_e)
print(T2)
#matriz de refraccion 3
n_l2=1.57565
R3=36.92
Ra_3=Ra(n_e,n_l2,R3)
print(Ra_3)
#matriz de traslacion 3
D3=15.11
T3=T(D3,n_l2)
print(T3)
#matriz de refraccion 4
n_l3=1.66764
R4=np.inf
Ra_4=Ra(n_l2,n_l3,R4)
print(Ra_4)
#matriz de traslacion 4
D4=2.31
T4=T(D4,n_l3)
print(T4)
#matriz de refraccion 5
R5=23.06
Ra_5=Ra(n_l3,n_e,R5)
print(Ra_5)
#matriz de traslacion 5
D5=22.5
T5=T(D5,n_e)
print(T5)
#matriz de refraccion 6
n_l4=1.56046
R6=-23.91
Ra_6=Ra(n_e,n_l4,R6)
print(Ra_6)
#matriz de traslacion 6
D6=1.92
T6=T(D6,n_l4)
print(T6)
#matriz de refraccion 7
n_l5=1.63128
R7=np.inf
Ra_7=Ra(n_l4,n_l5,R7)
print(Ra_7)
#matriz de traslacion 7
D7=7.77
T7=T(D7,n_l5)
print(T7)
#matriz de refraccion 8
R8=-36.92
Ra_8=Ra(n_l5,n_e,R8)
print(Ra_8)
#matriz de traslacion 8
D8=0.38
T8=T(D8,n_e)
print(T8)
#matriz de refraccion 9
n_l6=1.61286
R9=-1063.24
Ra_9=Ra(n_e,n_l6,R9)
print(Ra_9)
#matriz de traslacion 9
D9=6.73
T9=T(D9,n_l6)
print(T9)
#matriz de refraccion 10
R10=-48.88
Ra_10=Ra(n_l6,n_e,R10)
print(Ra_10)
Lista=[Ra_1,T1,Ra_2,T2,Ra_3,T3,Ra_4,T4,Ra_5,T5,Ra_6,T6,Ra_7,T7,Ra_8,T8,Ra_9,T9,Ra_10]

#calculamos la matriz del sistema con el simbolo @
M_sistema=Ra_1@T1@Ra_2@T2@Ra_3@T3@Ra_4@T4@Ra_5@T5@Ra_6@T6@Ra_7@T7@Ra_8@T8@Ra_9@T9@Ra_10
print(M_sistema)
print("**************")

#funcion de multiplicacion
def multiplica(lista):
    M=lista[0]
    for i in range(1,len(lista)):
        M=np.dot(M,lista[i])
    return M
M_sistema2=multiplica(Lista)
print(M_sistema2)
print("**************")






[[ 1.         -0.01265548]
 [ 0.          1.        ]]
[[1.         0.        ]
 [5.49240084 1.        ]]
[[1.         0.00338107]
 [0.         1.        ]]
[[1.   0.  ]
 [0.38 1.  ]]
[[ 1.         -0.01559182]
 [ 0.          1.        ]]
[[1.         0.        ]
 [9.58969314 1.        ]]
[[ 1. -0.]
 [ 0.  1.]]
[[1.         0.        ]
 [1.38519105 1.        ]]
[[1.        0.0289523]
 [0.        1.       ]]
[[ 1.   0. ]
 [22.5  1. ]]
[[1.        0.0234404]
 [0.        1.       ]]
[[1.         0.        ]
 [1.23040642 1.        ]]
[[ 1. -0.]
 [ 0.  1.]]
[[1.         0.        ]
 [4.76313079 1.        ]]
[[ 1.         -0.01709859]
 [ 0.          1.        ]]
[[1.   0.  ]
 [0.38 1.  ]]
[[1.00000000e+00 5.76407961e-04]
 [0.00000000e+00 1.00000000e+00]]
[[1.         0.        ]
 [4.17271183 1.        ]]
[[ 1.         -0.01253805]
 [ 0.          1.        ]]
[[ 5.99239573e-01 -9.22216212e-03]
 [ 6.90463771e+01  6.06173447e-01]]
**************
[[ 5.99239573e-01 -9.22216212e-03]
 [ 6.90463771e

In [150]:
#instanciamos una clase de formacion de imagen
fi=FormacionImagen(M_sistema,n=1,np=1,d=200)
print("distancia entre H y V")
print(fi.D())
print("distancia entre H' y V'")
print(fi.Dp())
print("distancia entre O y H")
print(fi.distanciaOH())
print("distancia entre H' y I")
print(fi.distanciaHpI())
print("distancia entre V' y I")
print(fi.distanciaVpI())
print("magnificacion lateral")
print(fi.mx())
print("magnificacion angular")
print(fi.ma())

distancia entre H y V
-43.45623318367238
distancia entre H' y V'
-42.704362417776565
distancia entre O y H
243.4562331836724
distancia entre H' y I
195.51688969599067
distancia entre V' y I
152.8125272782141
magnificacion lateral
-0.8030884530628777
magnificacion angular
-1.2451928504091008


##$Ejercicio\ 2$


In [151]:
#matriz de refraccion 1
n_e=1
n_l1=1.744
R1=62
Ra_1=Ra(n_e,n_l1,R1)
print("matriz de refraccion 1")
print(Ra_1)
#matriz de traslacion 1
D1=1.11
T1=T(D1,n_l1)
print("matriz de traslacion 1")
print(T1)
#matriz de refraccion 2
n_l2=1.649
R2=np.inf
Ra_2=Ra(n_l1,n_l2,R2)
print("matriz de refraccion 2")
print(Ra_2)
#matriz de traslacion 2
D2=0.74
T2=T(D2,n_l2)
print("matriz de traslacion 2")
print(T2)
#matriz de refraccin 3
R3=101.20
Ra_3=Ra(n_l2,n_e,R3)
print("matriz de refraccion 3")
print(Ra_3)
#matriz de traslacion 3
D3=2.78
T3=T(D3,n_e)
print("matriz de traslacion 3")
print(T3)
#matriz de refraccion 4
n_l3=1.649
R4=-101.20
Ra_4=Ra(n_e,n_l3,R4)
print("matriz de refraccion 4")
print(Ra_4)
#matriz de traslacion 4
D4=0.74
T4=T(D4,n_l3)
print("matriz de traslacion 4")
print(T4)
#matriz de refraccion 5
n_l4=1.744
R5=np.inf
Ra_5=Ra(n_l3,n_l4,R5)
print("matriz de refraccion 5")
print(Ra_5)
#matriz de traslacion 5
D5=1.11
T5=T(D5,n_l4)
print("matriz de traslacion 5")
print(T5)
#matriz de refraccion 6
R6=-62
Ra_6=Ra(n_l4,n_e,R6)
print("matriz de refraccion 6")
print(Ra_6)
M_sistema=Ra_1@T1@Ra_2@T2@Ra_3@T3@Ra_4@T4@Ra_5@T5@Ra_6
print("matriz del sistema")
print(M_sistema)
print("**************")

matriz de refraccion 1
[[ 1.    -0.012]
 [ 0.     1.   ]]
matriz de traslacion 1
[[1.         0.        ]
 [0.63646789 1.        ]]
matriz de refraccion 2
[[1. 0.]
 [0. 1.]]
matriz de traslacion 2
[[1.         0.        ]
 [0.44875682 1.        ]]
matriz de refraccion 3
[[1.         0.00641304]
 [0.         1.        ]]
matriz de traslacion 3
[[1.   0.  ]
 [2.78 1.  ]]
matriz de refraccion 4
[[1.         0.00641304]
 [0.         1.        ]]
matriz de traslacion 4
[[1.         0.        ]
 [0.44875682 1.        ]]
matriz de refraccion 5
[[ 1. -0.]
 [ 0.  1.]]
matriz de traslacion 5
[[1.         0.        ]
 [0.63646789 1.        ]]
matriz de refraccion 6
[[ 1.    -0.012]
 [ 0.     1.   ]]
matriz del sistema
[[ 0.97181891 -0.01110386]
 [ 5.00438486  0.97181891]]
**************


In [152]:
#matriz antes del diafragma
m_before_diafragma=Ra_1@T1@Ra_2@T2@Ra_3
print("matriz antes del diafragma")
print(m_before_diafragma)

matriz antes del diafragma
[[ 0.9869773  -0.00567047]
 [ 1.08522471  1.00695959]]


Si el diafragma esta en la mitad del sistema

In [153]:
fi=FormacionImagen(M_sistema,n=1,np=1,d=-2.78)
print("Distancia de la imagen al V'")
print(fi.distanciaVpI())

Distancia de la imagen al V'
-2.2965559597740697


In [154]:
#matriz despues del diafragma
m_after_diafragma=Ra_4@T4@Ra_5@T5@Ra_6
print("matriz despues del diafragma")
print(m_after_diafragma)

matriz despues del diafragma
[[ 1.00695959 -0.00567047]
 [ 1.08522471  0.9869773 ]]


In [155]:
#instanciamos la clase formacion de imagen
fi=FormacionImagen(M_sistema,n=1,np=1,d=2.78)
print("distancia entre H y V")
print(fi.D())
print("distancia entre H' y V'")
print(fi.Dp())
print("distancia entre H y F")
print(fi.foco_principal_objeto())
print("distancia entre H' y F'")
print(fi.foco_principal_imagen())
print("distancia entre O y H")
print(fi.distanciaOH())
print("distancia entre H' y I")
print(fi.distanciaHpI())
print("distancia entre V' y I")
print(fi.distanciaVpI())

distancia entre H y V
-2.537953583642531
distancia entre H' y V'
-2.537953583642531
distancia entre H y F
90.05873336168558
distancia entre H' y F'
90.05873336168558
distancia entre O y H
5.317953583642531
distancia entre H' y I
-5.651684644317809
distancia entre V' y I
-8.18963822796034


#### $Ejercicio\ de\ Parcial$

In [159]:
#indices de refraccion de las lentes
n_e=1
n_l1=1.4585
n_l2=1.6727
n_l3=1.6910
n_l4=1.7200
n_l5=1.6200
n_l6=1.7552
n_l7=1.7200
n_l8=1.6910
n_l9=1.6910

"""Lente 1***************************"""
#matriz de refraccion 1
R1=5.4309
Ra_1=Ra(n_e,n_l1,R1)
print("matriz de refraccion 1")
print(Ra_1)
#matriz de traslacion 1
D12=0.7220
T12=T(D12,n_l1)
print("matriz de traslacion 1")
print(T12)
#matriz de refraccion 2
R2=2.3942
Ra_2=Ra(n_l1,n_e,R2)
print("matriz de refraccion 2")
print(Ra_2)
"""Lente 1***************************"""

#matriz de traslacion 2
D23=1.2934
T23=T(D23,n_e)
print("matriz de traslacion 2")
print(T23)

"""Lente 2***************************"""
#matriz de refraccion 3
R3=-3.8629
Ra_3=Ra(n_e,n_l2,R3)
print("matriz de refraccion 3")
print(Ra_3)
#matriz de traslacion 3
D34=0.7140
T34=T(D34,n_l3)
print("matriz de traslacion 3")
print(T34)
#matriz de refraccion 4
R4=-5.5409
Ra_4=Ra(n_l2,n_e,R4)
print("matriz de refraccion 4")
print(Ra_4)
"""Lente 2***************************"""

#matriz de traslacion 4
D45=0.0115
T45=T(D45,n_e)
print("matriz de traslacion 4")
print(T45)

"""Lente 3***************************"""
#matriz de refraccion 5
R5=-16.0642
Ra_5=Ra(n_e,n_l3,R5)
print("matriz de refraccion 5")
print(Ra_5)
#matriz de traslacion 5
D56=1.6219
T56=T(D56,n_l3)
print("matriz de traslacion 5")
print(T56)
#matriz de refraccion 6
R6=-6.5538
Ra_6=Ra(n_l3,n_e,R6)
print("matriz de refraccion 6")
print(Ra_6)
"""Lente 3***************************"""

#matriz de traslacion 6
D67=0.0134
T67=T(D67,n_e)
print("matriz de traslacion 6")
print(T67)

"""Lente 45***************************"""
#matriz de refraccion 7
R7=4.3769
Ra_7=Ra(n_e,n_l4,R7)
print("matriz de refraccion 7")
print(Ra_7)
#matriz de traslacion 7
D78=1.6521
T78=T(D78,n_l4)
print("matriz de traslacion 7")
print(T78)
#matriz de refraccion 8
R8=-4.1619
Ra_8=Ra(n_l4,n_l5,R8)
print("matriz de refraccion 8")
print(Ra_8)
#matriz de traslacion 8
D89=0.4850
T89=T(D89,n_l5)
print("matriz de traslacion 8")
print(T89)
#matriz de refraccion 9
R9=9.8038
Ra_9=Ra(n_l5,n_e,R9)
print("matriz de refraccion 9")
print(Ra_9)
"""Lente 45***************************"""


#matriz de traslacion 9
D910=2.1154
T910=T(D910,n_e)
print("matriz de traslacion 9")
print(T910)


"""Lente 6***************************"""
#matriz de refraccion 10
R10=-3.8829
Ra_10=Ra(n_e,n_l6,R10)
print("matriz de refraccion 10")
print(Ra_10)
#matriz de traslacion 10
D1011=0.1769
T1011=T(D1011,n_l6)
print("matriz de traslacion 10")
print(T1011)
#matriz de refraccion 11
R11=5.4280
Ra_11=Ra(n_l6,n_e,R11)
print("matriz de refraccion 11")
print(Ra_11)
"""Lente 6***************************"""

#matriz de traslacion 11
D1112=0.0844
T1112=T(D1112,n_e)
print("matriz de traslacion 11")
print(T1112)


"""Lente 7***************************"""
#matriz de refraccion 12
R12=35.4552
Ra_12=Ra(n_e,n_l7,R12)
print("matriz de refraccion 12")
print(Ra_12)
#matriz de traslacion 12
D1213=0.3503
T1213=T(D1213,n_l7)
print("matriz de traslacion 12")
print(T1213)
#matriz de refraccion 13
R13=-3.2140
Ra_13=Ra(n_l7,n_e,R13)
print("matriz de refraccion 13")
print(Ra_13)
"""Lente 7***************************"""

#matriz de traslacion 13
D1314=0.01
T1314=T(D1314,n_e)
print("matriz de traslacion 13")
print(T1314)

"""Lente 8***************************"""
#matriz de refraccion 14
R14=3.2160
Ra_14=Ra(n_e,n_l8,R14)
print("matriz de refraccion 14")
print(Ra_14)
#matriz de traslacion 14
D1415=0.6218
T1415=T(D1415,n_l8)
print("matriz de traslacion 14")
print(T1415)
#matriz de refraccion 15
R15=-36.2242
Ra_15=Ra(n_l8,n_e,R15)
print("matriz de refraccion 15")
print(Ra_15)
"""Lente 8***************************"""

#matriz de traslacion 15
D1516=0.0004
T1516=T(D1516,n_e)
print("matriz de traslacion 15")
print(T1516)

"""Lente 9***************************"""
#matriz de refraccion 16
R16=2.0680
Ra_16=Ra(n_e,n_l9,R16)
print("matriz de refraccion 16")
print(Ra_16)
#matriz de traslacion 16
D1617=0.5136
T1617=T(D1617,n_l9)
print("matriz de traslacion 16")
print(T1617)
#matriz de refraccion 17
R17=1.6121
Ra_17=Ra(n_l9,n_e,R17)
print("matriz de refraccion 17")
print(Ra_17)
"""Lente 9***************************"""


#matriz del sistema
Lista=[Ra_1,T12,Ra_2,T23,Ra_3,T34,Ra_4,T45,Ra_5,T56,Ra_6,T67,Ra_7,T78,Ra_8,T89,Ra_9,T910,
       Ra_10,T1011,Ra_11,T1112,Ra_12,T1213,Ra_13,T1314,Ra_14,T1415,Ra_15,T1516,Ra_16,T1617,
       Ra_17]

matriz de refraccion 1
[[ 1.         -0.08442431]
 [ 0.          1.        ]]
matriz de traslacion 1
[[1.         0.        ]
 [0.49502914 1.        ]]
matriz de refraccion 2
[[1.         0.19150447]
 [0.         1.        ]]
matriz de traslacion 2
[[1.     0.    ]
 [1.2934 1.    ]]
matriz de refraccion 3
[[1.         0.17414378]
 [0.         1.        ]]
matriz de traslacion 3
[[1.         0.        ]
 [0.42223536 1.        ]]
matriz de refraccion 4
[[ 1.         -0.12140627]
 [ 0.          1.        ]]
matriz de traslacion 4
[[1.     0.    ]
 [0.0115 1.    ]]
matriz de refraccion 5
[[1.        0.0430149]
 [0.        1.       ]]
matriz de traslacion 5
[[1.         0.        ]
 [0.95913661 1.        ]]
matriz de refraccion 6
[[ 1.         -0.10543501]
 [ 0.          1.        ]]
matriz de traslacion 6
[[1.     0.    ]
 [0.0134 1.    ]]
matriz de refraccion 7
[[ 1.         -0.16449999]
 [ 0.          1.        ]]
matriz de traslacion 7
[[1.         0.        ]
 [0.96052326 1.        ]]


In [162]:
# Lente 1
print("Matriz de Lente 1:")
print(M_lente1)
print("")

# Traslación entre Lente 1 y Lente 2 (T23)
print("Traslación entre Lente 1 y Lente 2 (T23):")
print(T23)
print("")

# Lente 2
print("Matriz de Lente 2:")
print(M_lente2)
print("")

# Producto Lente 1 + T23 + Lente 2
M1_T23_M2 = M_lente1 @ T23 @ M_lente2
print("Matriz de Lente 1 * T23 * Lente 2:")
print(M1_T23_M2)
print("")

# Traslación entre Lente 2 y Lente 3 (T45)
print("Traslación entre Lente 2 y Lente 3 (T45):")
print(T45)
print("")

# Lente 3
print("Matriz de Lente 3:")
print(M_lente3)
print("")

# Producto Lente 2 + T45 + Lente 3
M2_T45_M3 = M_lente2 @ T45 @ M_lente3
print("Matriz de Lente 2 * T45 * Lente 3:")
print(M2_T45_M3)
print("")

# Traslación entre Lente 3 y Lente 45 (T67)
print("Traslación entre Lente 3 y Lente 45 (T67):")
print(T67)
print("")

# Lente 45
print("Matriz de Lente 45:")
print(M_lente45)
print("")

# Producto Lente 3 + T67 + Lente 45
M3_T67_M45 = M_lente3 @ T67 @ M_lente45
print("Matriz de Lente 3 * T67 * Lente 45:")
print(M3_T67_M45)
print("")

# Traslación entre Lente 45 y Lente 6 (T910)
print("Traslación entre Lente 45 y Lente 6 (T910):")
print(T910)
print("")

# Lente 6
print("Matriz de Lente 6:")
print(M_lente6)
print("")

# Producto Lente 45 + T910 + Lente 6
M45_T910_M6 = M_lente45 @ T910 @ M_lente6
print("Matriz de Lente 45 * T910 * Lente 6:")
print(M45_T910_M6)
print("")

# Traslación entre Lente 6 y Lente 7 (T1112)
print("Traslación entre Lente 6 y Lente 7 (T1112):")
print(T1112)
print("")

# Lente 7
print("Matriz de Lente 7:")
print(M_lente7)
print("")

# Producto Lente 6 + T1112 + Lente 7
M6_T1112_M7 = M_lente6 @ T1112 @ M_lente7
print("Matriz de Lente 6 * T1112 * Lente 7:")
print(M6_T1112_M7)
print("")

# Traslación entre Lente 7 y Lente 8 (T1314)
print("Traslación entre Lente 7 y Lente 8 (T1314):")
print(T1314)
print("")

# Lente 8
print("Matriz de Lente 8:")
print(M_lente8)
print("")

# Producto Lente 7 + T1314 + Lente 8
M7_T1314_M8 = M_lente7 @ T1314 @ M_lente8
print("Matriz de Lente 7 * T1314 * Lente 8:")
print(M7_T1314_M8)
print("")

# Traslación entre Lente 8 y Lente 9 (T1516)
print("Traslación entre Lente 8 y Lente 9 (T1516):")
print(T1516)
print("")

# Lente 9
print("Matriz de Lente 9:")
print(M_lente9)
print("")

# Producto Lente 8 + T1516 + Lente 9
M8_T1516_M9 = M_lente8 @ T1516 @ M_lente9
print("Matriz de Lente 8 * T1516 * Lente 9:")
print(M8_T1516_M9)
print("")

# Matriz del sistema total
M_sistema_total = (
    M_lente1 @ T23 @
    M_lente2 @ T45 @
    M_lente3 @ T67 @
    M_lente45 @ T910 @
    M_lente6 @ T1112 @
    M_lente7 @ T1314 @
    M_lente8 @ T1516 @
    M_lente9
)
print("Matriz del sistema total:")
print(M_sistema_total)

Matriz de Lente 1:
[[0.95820751 0.09907671]
 [0.49502914 1.09480029]]

Traslación entre Lente 1 y Lente 2 (T23):
[[1.     0.    ]
 [1.2934 1.    ]]

Matriz de Lente 2:
[[1.07352966 0.04381055]
 [0.42223536 0.94873798]]

Matriz de Lente 1 * T23 * Lente 2:
[[1.2080662  0.14159157]
 [2.51382564 1.12240249]]

Traslación entre Lente 2 y Lente 3 (T45):
[[1.     0.    ]
 [0.0115 1.    ]]

Matriz de Lente 3:
[[ 1.04125717 -0.06677006]
 [ 0.95913661  0.89887342]]

Matriz de Lente 2 * T45 * Lente 3:
[[ 1.16036536 -0.03233315]
 [ 1.36098555  0.82387417]]

Traslación entre Lente 3 y Lente 45 (T67):
[[1.     0.    ]
 [0.0134 1.    ]]

Matriz de Lente 45:
[[ 0.78668867 -0.13498018]
 [ 1.25299653  1.05616152]]

Matriz de Lente 3 * T67 * Lente 45:
[[ 0.7347787  -0.21094828]
 [ 1.89030276  0.81826526]]

Traslación entre Lente 45 y Lente 6 (T910):
[[1.     0.    ]
 [2.1154 1.    ]]

Matriz de Lente 6:
[[1.0196023  0.33635152]
 [0.10078624 1.01402243]]

Matriz de Lente 45 * T910 * Lente 6:
[[0.49737118 0

In [163]:
#calculamos la Matriz con un bucle
M_sistema=multiplica(Lista)
print("matriz del sistema")
print(M_sistema)

matriz del sistema
[[ 0.63816177 -0.27663607]
 [ 4.5789924  -0.41794175]]


In [165]:
#creamos una instancia de la clase FormacionImagen
fi=FormacionImagen(M_sistema,n=1,np=1,d=200)

print("distancia entre H y V")
print(fi.D())
print("distancia entre H' y V'")
print(fi.Dp())
print("distancia entre O y H")
print(fi.distanciaOH()) 
print("distancia entre H' y I")
print(fi.distanciaHpI())
print("distancia entre V' y I")
print(fi.distanciaVpI())
print("magnificacion lateral")
print(fi.mx())
print("magnificacion angular")
print(fi.ma())



distancia entre H y V
-1.3079936950356645
distancia entre H' y V'
-5.125657569083939
distancia entre O y H
201.30799369503566
distancia entre H' y I
3.6809560252878253
distancia entre V' y I
-1.4447015437961142
magnificacion lateral
-0.018285195524148534
magnificacion angular
-54.68905151598347
