<a href="https://colab.research.google.com/github/diperezp/Analisis_Se-al_2025_1/blob/main/Optica/OpticaGeometricaMatricial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#$Optica\ Geometrica\ Matricial$

##$Librerias\ a\ utilizar$

In [ ]:
import numpy as np                  #manejo de matrices
import math                         #libreria de matematicas
import matplotlib.pyplot as plt     #libreria para graficar

##$Matriz\ de\ refracción$
$$\begin{pmatrix} 1& -\textit{P} \\ 0 & 1\end{pmatrix}$$

$\textit{P}\rightarrow poder\ de\ la\ interfase$

$$P = \frac{n_t-n_i}{R}$$


*   $n_i \rightarrow indice\ de\  incidencia$
*   $n_t \rightarrow indice\ de\ refraccion$
*   $R  \rightarrow radio\ de\ la\ interfase$

In [ ]:
"""Esta funcion devuelve la matriz de de refraccion
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   nt=float()--->indice de refraccion del medio transmitido
   R=float()--->radio
   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de refraccion
   """
def Ra(n_i,n_t,R):
    P=(n_t-n_i)/R #poder del sistema
    return np.array([[1,-P],[0,1]])

print(Ra(1,1.5,10))

[[ 1.   -0.05]
 [ 0.    1.  ]]


##$Matriz\ de\ reflexión$

$$\begin{pmatrix} 1& \frac{2n_i}{R} \\ 0 & 1\end{pmatrix}$$


*   $n_i \rightarrow indice\ de\  incidencia$
*   $R  \rightarrow radio\ de\ la\ interfase$






In [ ]:
"""Esta funcion devuelve la matriz de reflexion de
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   R=float()--->radio de la interfase
   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de reflexion
   """
def Re(n_i,R):

    return np.array([[1,2*n_i/R],[0,1]])

print(Re(1,10))

[[1.  0.2]
 [0.  1. ]]


##$Matriz\ de\ translacion$

$$\begin{pmatrix} 1& 0 \\ \frac{D_{12}}{n_{12}} & 1\end{pmatrix}$$


*   $D_{12} \rightarrow distancias\ entre\ los\ dos\ vertices\ de\ la\ lente$
*   $n_{12}  \rightarrow indice\ de\ refraccion\ de\ la\ lente\$

In [ ]:
"""Esta funcion devuelve la matriz de reflexion de
   una interfase
   Paramaters:
   ----------------------
   D=float()--->distancia entre los dos vertices de la lente
   n=float()--->indice de refraccion de la lente
   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de traslación
   """
def T(D,n):
    return np.array([[1,0],[D/n,1]])
print(T(1,1.5))

[[1.         0.        ]
 [0.66666667 1.        ]]


##$Matriz\ de\ lente\ gruesa$

---
$M_{L_{gruesa}}=R_{aV'}T_{VV'}R_{aV}$

*   $R_{aV} → Matriz\ del\ primer\ vertice\ V$
*   $T_{VV'} → Matriz\ de\ traslacion\ entre\ vertices\  V→V'$
*   $R_{aV'} → Matriz\ del\ segundo\ vertice\ V'$

$$$$\begin{pmatrix} 1 - (\frac{P_{V'}D_l}{n_l})& -P_{V}-P_{V'}+(\frac{P_{V}P_{V'}D_l}{n_l}) \\ \frac{D_l}{n_l} &1 - (\frac{P_{V}D_l}{n_l})\end{pmatrix}$$ $$


*   $n_l → indice\ de\ refraccion\ de\ la\ lente$
*   $D_l → grosor\ de\ la\ lente$
*   $P_{V}=\frac{n_l-n}{R} → poder\ del\ vertice\ V $
*   $P_{V'}=\frac{n'-n_l}{R'} → poder\ del\ vertice\ V' $
*   $n → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V$
*   $n' → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V'$





In [ ]:
"""Esta funcion devuelve la matriz de de refraccion
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   R_1=float()--->radio del primer vertice
   n_l=float()--->indice de refraccion de la lente
   D=float()--->grosor de la lente
   R_2=float()--->radio del segundo vertice
   nt=float()--->indice de refraccion del medio transmitido

   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de refraccion
   """
def Lg(n,R_1,n_l,D,R_2,nt):
    P_1=(n_l-n)/R_1
    P_2=(nt-n_l)/R_2
    return np.array([[1-(P_1*D/n_l),-P_2-P_1+(P_1*P_2*D/n_l)],[D/n_l,1-(P_2*D/n_l)]])

def LgM(n,R_1,n_l,D,R_2,nt):
    Ra1=Ra(n,n_l,R_1)
    T1=T(D,n_l)
    Ra2=Ra(n_l,nt,R_2)
    return np.dot(np.dot(Ra1,T1),Ra2)

print(Lg(1,np.inf,1.5,0.15,-0.5,1))
print(LgM(1,np.inf,1.5,0.15,-0.5,1))

[[ 1.  -1. ]
 [ 0.1  0.9]]
[[ 1.  -1. ]
 [ 0.1  0.9]]


##$Matriz\ de\ lente\ delgada$

---
$M_{L_{gruesa}}=R_{aV'}T_{VV'}R_{aV}$

*   $R_{aV} → Matriz\ del\ primer\ vertice\ V$
*   $T_{VV'} → Matriz\ de\ traslacion\ entre\ vertices\  V→V'$
*   $R_{aV'} → Matriz\ del\ segundo\ vertice\ V'$

$$ M_{L_{gruesa}}$$  \begin{pmatrix} 1 - (\frac{P_{V'}D_l}{n_l})& -P_{V}-P_{V'}+(\frac{P_{V}P_{V'}D_l}{n_l}) \\ \frac{D_l}{n_l} &1 - (\frac{P_{V}D_l}{n_l})\end{pmatrix}$$ $$


*   $n_l → indice\ de\ refraccion\ de\ la\ lente$
*   $D_l ≈ 0 → lente\ delgada$
*   $P_{V}=\frac{n_l-n}{R} → poder\ del\ vertice\ V $
*   $P_{V'}=\frac{n'-n_l}{R'} → poder\ del\ vertice\ V' $
*   $n → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V$
*   $n' → indice\ de\ refraccion\ a\ la\ izquierda\ del\ vertice\ V'$

$$ M_{L_{delgada}}$$  \begin{pmatrix} 1 & -P_{L_{delgada}}\\ 0 &1\end{pmatrix}$$ $$

*   $P_{L_{delgada}}= P_{V}+P_{V'}$


$$P_{L_{delgada}}= \frac{n_l-n}{R} + \frac{n'-n_l}{R'}$$

$ para\ n=n'=1\ se\ tiene\ que:$

$$P_{L_{delgada}}= (n_l-1)\frac{1}{R} - \frac{1}{R'} → Ecuacion\ del\ fabricante\ $$

In [ ]:
"""Esta funcion devuelve la matriz de de refraccion
   una interfase
   Paramaters:
   ----------------------
   ni=float()--->indice de refraccion del medio incidente
   R_1=float()--->radio del primer vertice
   n_l=float()--->indice de refraccion de la lente
   R_2=float()--->radio del segundo vertice
   nt=float()--->indice de refraccion del medio transmitido

   Returns
   ---------------------
   ni=np.array(2,2)-> matriz de refraccion
   """

def Ld(n,R_1,n_l,R_2,nt):
    P_1=(n_l-n)/R_1
    P_2=(nt-n_l)/R_2
    return np.array([[1,-P_1-P_2],
                     [0,1]])

def LdM(n,R_1,n_l,R_2,nt):
    Ra1=Ra(n,n_l,R_1)
    T1=T(0,n_l)
    Ra2=Ra(n_l,nt,R_2)
    return np.dot(np.dot(Ra1,T1),Ra2)

print(Ld(1,10,1.5,np.inf,1))
print(LdM(1,10,1.5,np.inf,1))


[[ 1.   -0.05]
 [ 0.    1.  ]]
[[ 1.   -0.05]
 [ 0.    1.  ]]


##$$Planos\ principales$$


$M_{HH'}= T_{V'H'}M_{HH'}T_{VH}$

$T_{HV}=\begin{pmatrix} 1& 0 \\ \frac{D}{n} & 1\end{pmatrix}\\
M_{VV'}= \begin{pmatrix} M_{11} & M_{12} \\ M_{21} & M_{22}\end{pmatrix}\\
T_{H'V'}=\begin{pmatrix} 1& 0 \\ \frac{D'}{n'} & 1\end{pmatrix}$

$$M_{HH'}= \begin{pmatrix} M_{11}+\frac{M_{12}D}{n} & M_{12}\\ \frac{M_{11}D'}{n'}+\frac{M_{12}DD'}{nn'}+M_{21}+\frac{M_{22}D}{n}&M_{22}+\frac{M_{12}D'}{n'} \end{pmatrix}$$

$$T_{H'V'}=\begin{pmatrix} 1& -P_{sistema} \\ 0 & 1\end{pmatrix}$$

$\therefore$

$M_{11}+\frac{M_{12}D}{n}=1 ⇒ \overline{HV}=D=(\frac{n}{M_{12}})(1-M_{11})$

$M_{22}+\frac{M_{12}D'}{n'}=1 ⇒ \overline{V'H'}=D'=(\frac{n'}{M_{12}})(1-M_{22})$

$M_{12}=-P_{sistema}$

$P_{sistema}=\frac{nM_{11}}{D} + \frac{n'M_{22}}{D'}+\frac{nn'M_{21}}{DD'}$




In [ ]:
"""
Funcion devulve los parametros de los planos principales
relacionados a una matriz de un sistema optico
"""

class PlanosPrincipales():
    def __init__(self,matriz,n=1,np=1):
        self.matriz=matriz
        self.n=n
        self.np=np

    def D(self,n=1 # indice a la izquierda del sistema optico
          ):
        return (n/self.matriz[0,1])*(1-self.matriz[0,0])
    def Dp(self,n=1 #indice a la derecha del sistema optico
           ):
        return (n/self.matriz[0,1])*(1-self.matriz[1,1])
    def poder_sistema(self):
        return -self.matriz[0,1]
    def matriz_plano_principal(self):
        return np.array([[1,-self.poder_sistema()],[0,1]])

    def foco_principal_objeto(self,n=1 #indice a la izquierda del sistema optico
                              ):
        return n/self.poder_sistema()
    def foco_principal_imagen(self,n=1 #indice a la derecha del sistema optico
                              ):
        return n/self.poder_sistema()

## $ Formacion\ de\ Imagenes$


$M_{OI}=T_{H'I}M_{HH'}T_{OH}$
$=\begin{pmatrix} 1&0\\ \frac{s'}{n'}&1 \end{pmatrix} \begin{pmatrix} 1&-P_{sistema}\\ 0&1\end{pmatrix} \begin{pmatrix} 1&0\\ \frac{s}{n}&1\end{pmatrix}$


$$M_{OI}=\begin{pmatrix} 1-\frac{s}{n}P_{sistema}& P_{sistema}\\\frac{s'}{n'}+\frac{s}{n}-\frac{ss'}{nn'}P_{sistema}&1-\frac{s'}{n'}P_{sistema} \end{pmatrix}$$


$\text{Como se trata de una transformacion entre planos conjugados, entonces la matriz debe de tener la forma de:}$

$M_{OI}=\begin{pmatrix} \frac{n'}{n}m_{α}&M_{12}\\0&m_{x} \end{pmatrix} \therefore$

$\frac{n'}{s'}+\frac{n}{s}=P_{sistema}$

$m_{x}=1-\frac{s'}{n'}P_{sistema}$

$m_{α}=\frac{n}{n'}(1-\frac{s}{n}P_{sistema})$



# Nueva sección

In [ ]:
#clase de formacion de imagen
"""Falta corregir el codigo este codigo no sirve y no esta probado"""
class FormacionImagen(PlanosPrincipales):
    def __init__(self,matriz,n=1,np=1,d=0):
        super().__init__(matriz,n,np)
        self.d=d #distancia entre el objeto y el vertice V

    def distanciaOH(self):

      #calculamos la distancia entre el objeto y el plano H
      s= -self.D()+self.d
      return s
    def distanciaHpI(self):
      sp= self.np/(self.poder_sistema()-(self.n/self.distanciaOH()))
      return sp

    def distanciaVpI(self):
      return self.distanciaHpI()+self.Dp()

    def mx(self):
      mx=1-(self.distanciaHpI()/self.np)*self.poder_sistema()
      return mx

    def ma(self):
      return (self.n/self.np)*(1-(self.distanciaOH()/self.n)*self.poder_sistema())


##$Ejercicio\ del\ taller$

In [ ]:
#matriz de refraccion 1
n_e=1
n_l1=1.6186
R1=48.88
Ra_1=Ra(n_e,n_l1,R1)
print(Ra_1)
#matriz de traslacion 1
D1=8.89
T1=T(D1,n_l1)
print(T1)
#matriz de refraccion 2
R2=182.96
Ra_2=Ra(n_l1,n_e,R2)
print(Ra_2)
#matriz de traslacion 2
D2=0.38
T2=T(D2,n_e)
print(T2)
#matriz de refraccion 3
n_l2=1.57565
R3=36.92
Ra_3=Ra(n_e,n_l2,R3)
print(Ra_3)
#matriz de traslacion 3
D3=15.11
T3=T(D3,n_l2)
print(T3)
#matriz de refraccion 4
n_l3=1.66764
R4=np.inf
Ra_4=Ra(n_l2,n_l3,R4)
print(Ra_4)
#matriz de traslacion 4
D4=2.31
T4=T(D4,n_l3)
print(T4)
#matriz de refraccion 5
R5=23.06
Ra_5=Ra(n_l3,n_e,R5)
print(Ra_5)
#matriz de traslacion 5
D5=22.5
T5=T(D5,n_e)
print(T5)
#matriz de refraccion 6
n_l4=1.56046
R6=-23.91
Ra_6=Ra(n_e,n_l4,R6)
print(Ra_6)
#matriz de traslacion 6
D6=1.92
T6=T(D6,n_l4)
print(T6)
#matriz de refraccion 7
n_l5=1.63128
R7=np.inf
Ra_7=Ra(n_l4,n_l5,R7)
print(Ra_7)
#matriz de traslacion 7
D7=7.77
T7=T(D7,n_l5)
print(T7)
#matriz de refraccion 8
R8=-36.92
Ra_8=Ra(n_l5,n_e,R8)
print(Ra_8)
#matriz de traslacion 8
D8=0.38
T8=T(D8,n_e)
print(T8)
#matriz de refraccion 9
n_l6=1.61286
R9=-1063.24
Ra_9=Ra(n_e,n_l6,R9)
print(Ra_9)
#matriz de traslacion 9
D9=6.73
T9=T(D9,n_l6)
print(T9)
#matriz de refraccion 10
R10=-48.88
Ra_10=Ra(n_l6,n_e,R10)
print(Ra_10)
Lista=[Ra_1,T1,Ra_2,T2,Ra_3,T3,Ra_4,T4,Ra_5,T5,Ra_6,T6,Ra_7,T7,Ra_8,T8,Ra_9,T9,Ra_10]

#calculamos la matriz del sistema con el simbolo @
M_sistema=Ra_1@T1@Ra_2@T2@Ra_3@T3@Ra_4@T4@Ra_5@T5@Ra_6@T6@Ra_7@T7@Ra_8@T8@Ra_9@T9@Ra_10
print(M_sistema)
print("**************")

#funcion de multiplicacion
def multiplica(lista):
    M=lista[0]
    for i in range(1,len(lista)):
        M=np.dot(M,lista[i])
    return M
M_sistema2=multiplica(Lista)
print(M_sistema2)
print("**************")






[[ 1.         -0.01265548]
 [ 0.          1.        ]]
[[1.         0.        ]
 [5.49240084 1.        ]]
[[1.         0.00338107]
 [0.         1.        ]]
[[1.   0.  ]
 [0.38 1.  ]]
[[ 1.         -0.01559182]
 [ 0.          1.        ]]
[[1.         0.        ]
 [9.58969314 1.        ]]
[[ 1. -0.]
 [ 0.  1.]]
[[1.         0.        ]
 [1.38519105 1.        ]]
[[1.        0.0289523]
 [0.        1.       ]]
[[ 1.   0. ]
 [22.5  1. ]]
[[1.        0.0234404]
 [0.        1.       ]]
[[1.         0.        ]
 [1.23040642 1.        ]]
[[ 1. -0.]
 [ 0.  1.]]
[[1.         0.        ]
 [4.76313079 1.        ]]
[[ 1.         -0.01709859]
 [ 0.          1.        ]]
[[1.   0.  ]
 [0.38 1.  ]]
[[1.00000000e+00 5.76407961e-04]
 [0.00000000e+00 1.00000000e+00]]
[[1.         0.        ]
 [4.17271183 1.        ]]
[[ 1.         -0.01253805]
 [ 0.          1.        ]]
[[ 5.99239573e-01 -9.22216212e-03]
 [ 6.90463771e+01  6.06173447e-01]]
**************
[[ 5.99239573e-01 -9.22216212e-03]
 [ 6.90463771e

In [ ]:
#instanciamos una clase de formacion de imagen
fi=FormacionImagen(M_sistema,n=1,np=1,d=200)
print("distancia entre H y V")
print(fi.D())
print("distancia entre H' y V'")
print(fi.Dp())
print("distancia entre O y H")
print(fi.distanciaOH())
print("distancia entre H' y I")
print(fi.distanciaHpI())
print("distancia entre V' y I")
print(fi.distanciaVpI())
print("magnificacion lateral")
print(fi.mx())
print("magnificacion angular")
print(fi.ma())

distancia entre H y V
-43.45623318367238
distancia entre H' y V'
-42.704362417776565
distancia entre O y H
243.4562331836724
distancia entre H' y I
195.51688969599067
distancia entre V' y I
152.8125272782141
magnificacion lateral
-0.8030884530628777
magnificacion angular
-1.2451928504091008


##$Ejercicio\ 2$


In [ ]:
#matriz de refraccion 1
n_e=1
n_l1=1.744
R1=62
Ra_1=Ra(n_e,n_l1,R1)
print("matriz de refraccion 1")
print(Ra_1)
#matriz de traslacion 1
D1=1.11
T1=T(D1,n_l1)
print("matriz de traslacion 1")
print(T1)
#matriz de refraccion 2
n_l2=1.649
R2=np.inf
Ra_2=Ra(n_l1,n_l2,R2)
print("matriz de refraccion 2")
print(Ra_2)
#matriz de traslacion 2
D2=0.74
T2=T(D2,n_l2)
print("matriz de traslacion 2")
print(T2)
#matriz de refraccin 3
R3=101.20
Ra_3=Ra(n_l2,n_e,R3)
print("matriz de refraccion 3")
print(Ra_3)
#matriz de traslacion 3
D3=2.78
T3=T(D3,n_e)
print("matriz de traslacion 3")
print(T3)
#matriz de refraccion 4
n_l3=1.649
R4=-101.20
Ra_4=Ra(n_e,n_l3,R4)
print("matriz de refraccion 4")
print(Ra_4)
#matriz de traslacion 4
D4=0.74
T4=T(D4,n_l3)
print("matriz de traslacion 4")
print(T4)
#matriz de refraccion 5
n_l4=1.744
R5=np.inf
Ra_5=Ra(n_l3,n_l4,R5)
print("matriz de refraccion 5")
print(Ra_5)
#matriz de traslacion 5
D5=1.11
T5=T(D5,n_l4)
print("matriz de traslacion 5")
print(T5)
#matriz de refraccion 6
R6=-62
Ra_6=Ra(n_l4,n_e,R6)
print("matriz de refraccion 6")
print(Ra_6)
M_sistema=Ra_1@T1@Ra_2@T2@Ra_3@T3@Ra_4@T4@Ra_5@T5@Ra_6
print("matriz del sistema")
print(M_sistema)
print("**************")

matriz de refraccion 1
[[ 1.    -0.012]
 [ 0.     1.   ]]
matriz de traslacion 1
[[1.         0.        ]
 [0.63646789 1.        ]]
matriz de refraccion 2
[[1. 0.]
 [0. 1.]]
matriz de traslacion 2
[[1.         0.        ]
 [0.44875682 1.        ]]
matriz de refraccion 3
[[1.         0.00641304]
 [0.         1.        ]]
matriz de traslacion 3
[[1.   0.  ]
 [2.78 1.  ]]
matriz de refraccion 4
[[1.         0.00641304]
 [0.         1.        ]]
matriz de traslacion 4
[[1.         0.        ]
 [0.44875682 1.        ]]
matriz de refraccion 5
[[ 1. -0.]
 [ 0.  1.]]
matriz de traslacion 5
[[1.         0.        ]
 [0.63646789 1.        ]]
matriz de refraccion 6
[[ 1.    -0.012]
 [ 0.     1.   ]]
matriz del sistema
[[ 0.97181891 -0.01110386]
 [ 5.00438486  0.97181891]]
**************


In [ ]:
#matriz antes del diafragma
m_before_diafragma=Ra_1@T1@Ra_2@T2@Ra_3
print("matriz antes del diafragma")
print(m_before_diafragma)

matriz antes del diafragma
[[ 0.9869773  -0.00567047]
 [ 1.08522471  1.00695959]]


Si el diafragma esta en la mitad del sistema

In [ ]:
fi=FormacionImagen(M_sistema,n=1,np=1,d=-2.78)
print("Distancia de la imagen al V'")
print(fi.distanciaVpI())

Distancia de la imagen al V'
-2.2965559597740697


In [ ]:
#matriz despues del diafragma
m_after_diafragma=Ra_4@T4@Ra_5@T5@Ra_6
print("matriz despues del diafragma")
print(m_after_diafragma)

matriz despues del diafragma
[[ 1.00695959 -0.00567047]
 [ 1.08522471  0.9869773 ]]


In [ ]:
#instanciamos la clase formacion de imagen
fi=FormacionImagen(M_sistema,n=1,np=1,d=2.78)
print("distancia entre H y V")
print(fi.D())
print("distancia entre H' y V'")
print(fi.Dp())
print("distancia entre H y F")
print(fi.foco_principal_objeto())
print("distancia entre H' y F'")
print(fi.foco_principal_imagen())
print("distancia entre O y H")
print(fi.distanciaOH())
print("distancia entre H' y I")
print(fi.distanciaHpI())
print("distancia entre V' y I")
print(fi.distanciaVpI())

distancia entre H y V
-2.537953583642531
distancia entre H' y V'
-2.537953583642531
distancia entre H y F
90.05873336168558
distancia entre H' y F'
90.05873336168558
distancia entre O y H
5.317953583642531
distancia entre H' y I
-5.651684644317809
distancia entre V' y I
-8.18963822796034
